[Process]
Sleep=9000
Name=- JigA
Manual=False
AfterTimeOut=20000
PLCWrite=True
' 0: Rework, 1: Fail
ResultStandard=0
SavePath=D:\InspAft

[Model77]
Slot=24
Layer=4
Range=455
Angle=1.5
XOffSet=-8
YOffSet=-8

[Model76]
Slot=12
Layer=4
Range=515
Angle=183.7
XOffSet=-8
YOffSet=-8

[PLC]
IP=0
Area=D

ReadStatus=31202
WriteStatus=31400

ReadInspectionData=32000
ReadAfterPath=31030

WriteReWorkData=39000
WriteAfterResult=31406
Port=0

;검사모드(1 = 전 검사, 2 = 후검사)
;Jig A=31205
;Jig B=40205
ReadInspectModeReq=31205

;3D Scan 시작, 끝, 정지
;Jig A=31001
;Jig B=40001
ReadInspectResp=31001

;Jig A=31400
;Jig B=40400
ReadInspectComplete=31400


[Coulmn]
Col1=Probability,55
Col2=OldResult,0
Col3=Height 1,0
Col4=Height 2,0
Col5=Height C,0
Col6=Width0,0
Col7=Width1,0
Col8=Width2,0
Col9=Area,0
Col10=Type,0

[DB]
Use=False
IP=127.0.0.1
Catagory=LGE_INSPECTION
ID=sa
PW=hubis777
