//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// IWS.rc에서 사용되고 있습니다.
//
#define IDC_BUTTION_SAVEPEN             3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW_HOME               101
#define IDD_CAMERA_VIEW_DLG             108
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_IWSTYPE                     130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDS_APPNAME                     307
#define ID_VIEW_DRAWPROPERTIESWND       310
#define IDB_CAD_RIBBON                  310
#define ID_VIEW_DRAWCOMMANDWND          311
#define IDD_DIALOG_LASERPEN             311
#define ID_VIEW_JOBLISTWND              312
#define IDD_DIALOG_SCANNER              312
#define IDC_LIST_JOBLIST                313
#define IDD_DIALOG_BASE                 313
#define ID_BUTTON_JOBLIST_UP            314
#define ID_BUTTON_JOBLIST_DOWN          315
#define IDB_SPLASH                      316
#define ID_VIEW_LIVECCDWND              316
#define ID_VIEW_WORK                    317
#define IDD_DIALOG_CAD_ROUND            318
#define IDC_STATIC_CAD                  318
#define IDD_FORMVIEW                    319
#define IDD_FORMVIEW_VRS                319
#define IDC_GRID_WORKLIST               319
#define ID_GRID_DWGJOB                  320
#define IDD_DIALOG_MANUAL_SCAN          321
#define IDB_TITLE                       323
#define IDB_BITMAP1                     324
#define IDB_OPERATION                   324
#define IDD_DIALOG_WORK_STAGE           325
#define IDD_DIALOG_HAIRPIN_GEN          327
#define IDD_DIALOG_MATRIX               328
#define IDB_HAIRPIN                     329
#define IDD_GRAB_DLG                    330
#define IDD_DIALOG_MANUAL_WORK          331
#define IDI_ICON_DOWNSLOW               333
#define IDI_ICON_DOWNFAST               334
#define IDI_ICON_LEFTSLOW               335
#define IDI_ICON_LEFTFAST               336
#define IDI_ICON_RIGHTSLOW              337
#define IDI_ICON_RIGHTFAST              338
#define IDI_ICON_UPSLOW                 339
#define IDI_ICON_UPFAST                 340
#define IDD_DIALOG_WAIT_WORK            342
#define IDD_DIALOG_RECIPELIST           344
#define IDD_DIALOG_HAIPPIN_SET          346
#define IDD_DIALOG_VSCANIMG_POS         347
#define IDR_ACCELERATOR_IWS             348
#define IDD_DIALOG_HATCH_PATTERN        348
#define IDD_DIALOG_POWER_PROFILE        349
#define IDD_DIALOG_LASERPEN_CW          350
#define IDD_DIALOG_LASERPEN_PULSESHAPE  351
#define IDD_DIALOG_PATHVIEW             352
#define IDD_DIALOG_WELDPATH             352
#define IDD_DIALOG_LICENSE              357
#define IDD_DIALOG_WAIT_WORK2           357
#define IDD_DIALOG_LOGIN                359
#define IDB_DRAW_SMALL                  360
#define IDD_DIALOG_INSPECt_RESULTS      360
#define IDD_DIALOG_VSCANING_CALIB       361
#define IDD_DIALOG_PASSWORD             363
#define IDD_DIALOG_HAIRPIN_PATTERN      365
#define IDD_DIALOG_HAIRPIN_OFFSET       367
#define IDD_DIALOG_VSCANING_CALIB_SCAN  368
#define IDD_DIALOG_VSCANING_CALIB_LEARN 369
#define IDD_DIALOG_VSCANING_CALIB_STICHING 370
#define IDD_DIALOG_VSCANING_CALIB_CONF_GRID 371
#define IDD_DIALOG_LASERPEN_HIDDERN     372
#define IDD_DIALOG_LASER_PRGNO          375
#define IDD_DIALOG_MATRIX_PCC           376
#define IDD_DIALOG_REWORK_LIST          377
#define IDD_DIALOG_2D_INSPECTION_SET    380
#define IDD_DIALOG_SORTIE_MAP           382
#define IDC_CORR_FILE_FIND              1000
#define IDC_EDIT_PENID                  1001
#define IDC_EDIT_FREQUENCY              1002
#define IDC_EDIT_PULSEWIDTH             1003
#define IDC_BTN_LOAD_IMAGE2             1003
#define IDC_EDIT_JUMPSPEED              1004
#define IDC_EDIT_JUMPDELAY              1005
#define IDC_SCALE_FACTOR_CHANGE         1005
#define IDC_EDIT_WELDSPEED              1006
#define IDC_SCALE_FACTOR                1006
#define IDC_EDIT_OFFDELAY               1007
#define IDC_EDIT_WELDDELAY              1008
#define IDC_SCALE_RATE_KX               1008
#define IDC_CAM_VIEW                    1008
#define IDC_EDIT_ONDELAY                1009
#define IDC_SCALE_RATE_CHANGE           1009
#define IDC_EDIT_POLYDELAY              1010
#define IDC_SCALE_RATE_KY               1010
#define IDC_EDIT_LASERPOWER             1011
#define IDC_ROTATION                    1011
#define IDC_COMBOBOXEX_LASERPENS        1012
#define IDC_AUTO_CHANGE                 1013
#define IDC_EDIT_WB_FREQ                1013
#define IDC_MFCBUTTON1                  1014
#define IDC_MFCBUTTON_LASERPEN_APPLY    1014
#define IDC_LASER_EMISSION              1014
#define IDC_OFFSETX                     1015
#define IDC_GRID_MARK                   1015
#define IDC_EDIT_WB_LONGI               1015
#define IDC_BASE_SIZE_CHANGE            1016
#define IDC_LASER_ON                    1016
#define IDC_EDIT_WB_TRANSE              1016
#define IDC_OFFSETY                     1017
#define IDC_DIR_MARK                    1017
#define IDC_BTN_CALIB_FULL_IMAGE        1017
#define IDC_COMBOBOXEX_WVTABLE          1017
#define IDC_MFCBUTTON_ADD_ROW           1017
#define IDC_BASE_SIZE                   1018
#define IDC_SCAN_MOVE                   1018
#define IDC_BTN_SCAN_CALIB_IMAGE        1018
#define IDC_MFCBUTTON_DEL_ROW           1018
#define IDC_MFCEDITBROWSE_CORR_FILE     1019
#define IDC_REAL_SIZEX                  1020
#define IDC_BUTTON1                     1020
#define IDC_BUTTON_REFRESH_WORKLIST     1020
#define IDC_BUTTON_LASER_SIMULATION     1020
#define IDC_BTN_LINE_GAUGE              1020
#define IDC_BUTTON_WORK_STOP            1020
#define IDC_BUTTON_SELECT_RECIPE        1020
#define IDC_BTN_LIGHT_POWER             1020
#define IDC_BUTTON_UPDATE               1020
#define IDC_BUTTON_SNAP_IMAGE           1020
#define IDC_APPLY                       1020
#define IDC_BUTTON_TEST                 1020
#define IDC_BUTTON_CHANGE               1020
#define IDC_BUTTON_PLC_UPDATE           1020
#define IDC_BUTTON_ADD                  1020
#define IDC_BUTTON_RCP_ENABLE           1020
#define IDC_BUTTON_2D_PATH_SET          1020
#define IDC_REAL_SIZEY                  1021
#define IDC_BUTTON2                     1021
#define IDC_BUTTON_MANUAL_START         1021
#define IDC_BUTTON_SCAN_MOVE_YP         1021
#define IDC_BTN_LOAD_SCAN_IMG_MERGE2    1021
#define IDC_BTN_SCAN_MOVE_YP            1021
#define IDC_BUTTON_UNSELECT_RECIPE      1021
#define IDC_BUTTON_COPY                 1021
#define IDC_BUTTON_RES_SAVE             1021
#define IDC_BUTTON_MOVE_TO_ORIGIN       1021
#define IDC_BUTTON_SCAN_CALIBRATION     1021
#define IDC_BUTTON_ROI_APPLY            1021
#define IDC_BUTTON_IWS_UPDATE           1021
#define IDC_BUTTON_DELETE               1021
#define IDC_BTN_SET_HREF                1021
#define IDC_BUTTON_ALL_SET              1021
#define IDC_EDIT1                       1022
#define IDC_EDIT_LOG                    1022
#define IDC_EDIT_HAIRPIN_SIZE           1022
#define IDC_BUTTON_SCAN_MOVE_YN         1022
#define IDC_BTN_SCAN_MOVE_YN            1022
#define IDC_BUTTON_UNSELECT_ALL         1022
#define IDC_BUTTON_COPY2                1022
#define IDC_BUTTON_PASTE                1022
#define IDC_BUTTON_RES_IMPORT           1022
#define IDC_BUTTON_CALC                 1022
#define IDC_BUTTON_DELETE2              1022
#define IDC_CHECK1                      1023
#define IDC_CHECK_SIMULATION            1023
#define IDC_EDIT_SLOT_STARTANG          1023
#define IDC_EDIT2                       1023
#define IDC_BUTTON_MANUAL_START2        1023
#define IDC_BUTTON_DETECT_STATOR        1023
#define IDC_BUTTON_SCAN_MOVE_XP         1023
#define IDC_BTN_SCAN_MOVE_XP            1023
#define IDC_CHECK_WOBBEL                1023
#define IDC_BUTTON_SELECT_DOWN          1023
#define IDC_CHECK_SHOW_GRID_LINE        1023
#define IDC_CHECK_USE_1ST_PETTERN       1023
#define IDC_BUTTON_CLEAR                1023
#define IDC_CHECK_SAVE_HRESUT           1023
#define IDC_MFCBUTTON_SCANNER_APPLY     1024
#define IDC_BUTTON_REFRESH_WORKLIST2    1024
#define IDC_EDIT_NUM_LAYER              1024
#define IDC_BUTTON_SCAN_MOVE_XN         1024
#define IDC_BTN_SCAN_MOVE_XN            1024
#define IDC_EDIT_HP_2ND_WIDTH           1024
#define IDC_BUTTON_SELECT_UP            1024
#define IDC_CHECK_POWER_SHAPE           1024
#define IDC_EDIT_GRID_SIZE_MM           1024
#define IDC_CHECK_SHOW_COPY_AREA        1024
#define IDC_EDIT_DEGREE34               1024
#define IDC_BUTTON_APPLY                1024
#define IDC_BUTTON_LASER_GUIDE          1025
#define IDC_EDIT_WELD_REPEAT_P0         1025
#define IDC_BUTTON_SCAN_MOVE_ORG        1025
#define IDC_BTN_SCAN_MOVE_ORG           1025
#define IDC_EDIT_HP_REPEAT_P0           1025
#define IDC_EDIT_IMG_X                  1025
#define IDC_EDIT_DRAW_SLOT              1025
#define IDC_EDIT_GRID_SIZE_PX           1025
#define IDC_CHECK_USE_2ND_PETTERN       1025
#define IDC_EDIT_DEGREE78               1025
#define IDC_BUTTON_SAVE                 1025
#define IDC_EDIT_WELD_REPEAT_P1         1026
#define IDC_BUTTON_SCAN_STATOR          1026
#define IDC_BTN_ACQ_WELDPT              1026
#define IDC_EDIT_HP_REPEAT_P1           1026
#define IDC_EDIT_IMG_Y                  1026
#define IDC_BUTTON_MATRIX_VSCAN         1026
#define IDC_EDIT_ROUND                  1027
#define IDC_FREQUENCY                   1027
#define IDC_BUTTON_LASER_LASER          1027
#define IDC_EDIT_WELD_REPEAT_P0P1       1027
#define IDC_EDIT_HP_REPEAT_P0P1         1027
#define IDC_BTN_CALIB_ROAD              1027
#define IDC_BTN_CALIB_LOAD              1027
#define IDC_EDIT_IMG_CX                 1027
#define IDC_EDIT_HP_REPEAT_P2           1027
#define IDC_EDIT_WELD_REPEAT_P2         1027
#define IDC_EDIT_CEN_MODEL1_X           1027
#define IDC_EDIT_SCAN_XMIN              1027
#define IDC_BUTTON_MATRIX_PCC           1027
#define IDC_PULSE_WIDTH                 1028
#define IDC_EDIT_NUM_SLOT               1028
#define IDC_BUTTON_RESET_DETECTION      1028
#define IDC_EDIT_REFIMG_HEIGHT          1028
#define IDC_BTN_CALIB_SAVE              1028
#define IDC_EDIT_IMG_CY                 1028
#define IDC_EDIT_VSCAN_EY               1028
#define IDC_EDIT_HP_OVERLEN             1028
#define IDC_EDIT_SCAN_YMIN              1028
#define IDC_STC_READY                   1029
#define IDC_LASER_ON_TIME               1029
#define IDC_STC_ALARM                   1029
#define IDC_EDIT_WELD_PEN_P0            1029
#define IDC_BUTTON_CLEAR_LOG            1029
#define IDC_BTN_CALIB_MODIFY            1029
#define IDC_MFCEDITBROWSE_CCD_FILE      1029
#define IDC_EDIT_LIGHT_POWER            1029
#define IDC_EDIT_SCAN_XMAX              1029
#define IDC_EDIT_REPAIR_POWER           1029
#define IDC_EDIT_PTN_ROTATION_ANGLE     1029
#define IDC_EDIT_HP_2ND_WIDTH2          1029
#define IDC_STC_POWERON                 1030
#define IDC_GRID_SIZE                   1030
#define IDC_EDIT_WELD_PEN_P1            1030
#define IDC_BUTTON_SCAN_INSPECTION      1030
#define IDC_EDIT_CEN_MODEL1_Y           1030
#define IDC_EDIT_SCAN_YMAX              1030
#define IDC_STC_PS_ACTIVE               1031
#define IDC_SCAN_MOVEX                  1031
#define IDC_STC_LASER_TEMP              1031
#define IDC_EDIT_WELD_PEN_P0P1          1031
#define IDC_EDIT_WELD_PEN_P2            1031
#define IDC_EDIT_CEN_MODEL2_X           1031
#define IDC_EDIT_SCAN_OVERLAP_P         1031
#define IDC_BUTTON_MANUAL_START3        1031
#define IDC_BUTTON_SNAP                 1031
#define IDC_STC_EMISSION                1032
#define IDC_GRID_CNT                    1032
#define IDC_STC_LASER_FAULT             1032
#define IDC_EDIT_HAIRPIN_SIZE_W         1032
#define IDC_BUTTON_LIGHT                1032
#define IDC_EDIT_CEN_MODEL2_Y           1032
#define IDC_EDIT_SCAN_OVERLAPX_MM       1032
#define IDC_STC_DO_ERR_RESET            1033
#define IDC_SCAN_MOVEY                  1033
#define IDC_EDIT_HAIRPIN_SIZE_WD        1033
#define IDC_EDIT_CEN_MODEL3_X           1033
#define IDC_BUTTON_COMPLETE             1033
#define IDC_BUTTON_DO_SCAN              1033
#define IDC_STC_DO_EMISSION             1034
#define IDC_SCAN_SPEED                  1034
#define IDC_EDIT_PREQ_P1                1034
#define IDC_EDIT_CEN_MODEL3_Y           1034
#define IDC_BUTTON_DO_LEARN             1034
#define IDC_CORR_FULL_NAME              1035
#define IDC_STC_DO_GUIDE                1035
#define IDC_POWER                       1035
#define IDC_EDIT_PREQ_P2                1035
#define IDC_EDIT_CEN_MODEL4_X           1035
#define IDC_BUTTON_DO_SAVE_LEARN        1035
#define IDC_BUTTON_INIT_PARAM           1035
#define IDC_COMBO_LASERPENS             1036
#define IDC_EDIT_CEN_MODEL4_Y           1036
#define IDC_EDIT_PREQ_P3                1036
#define IDC_EDIT_OVERLEN                1036
#define IDC_BUTTON_DO_LOAD_LEARN        1036
#define IDC_BUTTON_CALC_STICHING_PARAM  1036
#define IDC_EDIT_HP_ROTATION            1036
#define IDC_STC_LASER_DI0               1037
#define IDC_RATIO_PWR                   1037
#define IDC_BUTTON_DO_CALIB_MERGE       1037
#define IDC_EDIT_REPAIR_SPEED           1037
#define IDC_EDIT_HP_ROTATION2           1037
#define IDC_EDIT_SORTIE_CNT             1037
#define IDC_STC_LASER_DI1               1038
#define IDC_RATIO_SPD                   1038
#define IDC_EDIT_STRENGTH               1038
#define IDC_EDIT_HAIRPIN_SIZE_WD2       1038
#define IDC_STC_LASER_DI2               1039
#define IDC_EDIT_SCAN_OVERLAPY_MM       1039
#define IDC_STC_LASER_DI3               1040
#define IDC_BUTTON_SET_STRENGTH         1040
#define IDC_STC_LASER_DI4               1041
#define IDC_BUTTON_SET_GRID_INFO        1041
#define IDC_STC_LASER_DI5               1042
#define IDC_EDIT_Z2_MAX                 1042
#define IDC_EDIT_STRENGTH_MIN           1042
#define IDC_STC_LASER_DI6               1043
#define IDC_EDIT_Z2_CNT                 1043
#define IDC_EDIT_STRENGTH3              1043
#define IDC_EDIT_STRENGTH_MAX           1043
#define IDC_STC_LASER_DI7               1044
#define IDC_EDIT_Z3_MIN                 1044
#define IDC_EDIT_Z3_MAX                 1045
#define IDC_STC_LASER_DO0               1046
#define IDC_GB_UTIL                     1046
#define IDC_EDIT_Z3_CNT                 1046
#define IDC_EDIT_Z4_MIN                 1047
#define IDC_EDIT_Z4_MAX                 1048
#define IDC_EDIT_Z4_CNT                 1049
#define IDC_STC_STATE_LASER             1050
#define IDC_EDIT_Z5_MIN                 1050
#define IDC_STC_STATE_GUIDE             1051
#define IDC_EDIT_Z5_MAX                 1051
#define IDC_STC_SIMULATION              1052
#define IDC_EDIT_Z5_CNT                 1052
#define IDC_STC_DOWORK                  1053
#define IDC_EDIT_Z6_MIN                 1053
#define IDC_STC_LASER_DO1               1054
#define IDC_STC_SIMULATION2             1054
#define IDC_STC_HEAD_STATE              1054
#define IDC_STATUS_INTERFACE            1054
#define IDC_EDIT_Z6_MAX                 1054
#define IDC_STC_LASER_DO2               1055
#define IDC_STC_STATE_LIGHT             1055
#define IDC_EDIT_Z6_CNT                 1055
#define IDC_STC_LASER_DO3               1056
#define IDC_EDIT_Z7_MIN                 1056
#define IDC_STC_LASER_DO4               1057
#define IDC_EDIT_Z7_MAX                 1057
#define IDC_STC_LASER_DO5               1058
#define IDC_EDIT_Z7_CNT                 1058
#define IDC_STC_LASER_DO6               1059
#define IDC_EDIT_Z8_MIN                 1059
#define IDC_STC_LASER_DO7               1060
#define IDC_EDIT_Z8_MAX                 1060
#define IDC_STC_LASER_DO8               1061
#define IDC_EDIT_Z8_CNT                 1061
#define IDC_STC_LASER_DO9               1062
#define IDC_EDIT_Z9_MIN                 1062
#define IDC_STC_LASER_DO10              1063
#define IDC_EDIT_Z9_MAX                 1063
#define IDC_STC_LASER_DO11              1064
#define IDC_EDIT_Z9_CNT                 1064
#define IDC_EDIT_Z10_MIN                1065
#define IDC_STATIC_WORKDISPLAY          1066
#define IDC_EDIT_Z10_MAX                1066
#define IDC_STC_GRID_DIO                1067
#define IDC_EDIT_Z1_CNT10               1067
#define IDC_EDIT_Z10_CNT                1067
#define IDC_PICT_HISTO                  1068
#define IDC_STC_GRID_WORK               1068
#define IDC_STC_GRID_PLC                1068
#define IDC_STC_GRID_JOBLIST            1069
#define IDC_STC_LABEL_DIO               1070
#define IDC_STC_LABEL_JOBLIST           1071
#define IDC_STC_LABEL_PLC               1071
#define IDC_STC_LABEL_WORKLIST          1072
#define IDC_STC_LABEL_CONTROL           1073
#define IDC_RADIO2                      1073
#define IDC_STATIC_CAD_VIEW             1073
#define IDC_RADIO_ZAXIS_COMP            1073
#define IDC_STATIC_LAYER_DIAMETER       1074
#define IDC_STC_LABEL_SYSTEMSTATUS      1074
#define IDC_STATIC_GRID_WORKVIEW        1074
#define IDC_STC_LABEL_TACTTIME          1074
#define IDC_RADIO_ZAXIS_COMP2           1074
#define IDC_STC_LABEL_SYSTEM            1075
#define IDC_STATIC_DESC                 1079
#define IDC_STC_DISTANCE                1080
#define IDC_RADIO_WORKALL               1081
#define IDC_STC_SCAN_CURRPOS            1081
#define IDC_RADIO3                      1082
#define IDC_COMBO_WORKLIST              1082
#define IDC_MFCPROPERTYGRID_COMMPARAM   1083
#define IDC_GB_HISTO                    1089
#define IDC_GB_UTILITY                  1090
#define IDC_BUTTON3                     1091
#define IDC_BTN_BRIGHTNESS_CALIB        1091
#define IDC_BUTTON_ONLINE               1091
#define IDC_BUTTON_SET_GRID_PARAM       1091
#define IDC_BUTTON_FIND_ALL             1091
#define IDC_BTN_POS_PATH_JIGA           1091
#define IDC_BTN_SCAN_CALIB_IMG          1092
#define IDC_BUTTON_OFFLINE              1092
#define IDC_BTN_POS_PATH_JIGB           1092
#define IDC_BTN_SCAN4_CAL_BRIGH         1093
#define IDC_EDIT_SCAN_MOVESTEP          1099
#define IDC_STATUS_PLC                  1100
#define IDC_STATUS_LASER                1101
#define IDC_STATIC_MESSAGE              1101
#define IDC_STATUS_SCANNER              1102
#define IDC_STATIC_RCP_NUMBER           1103
#define IDC_STATUS_CCD                  1104
#define IDC_STATIC_RCP_MODEL            1105
#define IDC_STATIC_SELECT_MODEL         1106
#define IDC_STATUS_WORKING              1106
#define IDC_STATIC_RCP_MODEL2           1107
#define IDC_STATIC_PLC_JIG              1108
#define IDC_STATIC_PLC_WorkWeld         1109
#define IDC_STATIC_PLC_MODELNO          1109
#define IDC_EDIT_DETECT_RANGE           1110
#define IDC_LIST_RECIPE_IN_FOLDER       1111
#define IDC_STATIC_PLC_WorkMode         1111
#define IDC_LIST_SELECTED_RECIPE        1112
#define IDC_EDIT_HP_LENGTH              1112
#define IDC_STATIC_RCP_LAST             1112
#define IDC_EDIT_HP_WIDTH               1113
#define IDC_EDIT_1ST_ENERGY             1114
#define IDC_EDIT_REFIMG_CX              1115
#define IDC_EDIT_VSCAN_SX               1115
#define IDC_EDIT_2ND_ENERGY             1115
#define IDC_EDIT_REFIMG_CY              1116
#define IDC_EDIT_VSCAN_SY               1116
#define IDC_EDIT_TOTAL_ENERGY           1116
#define IDC_EDIT_REFIMG_WIDTH           1117
#define IDC_EDIT_VSCAN_EX               1117
#define IDC_EDIT_TOTAL_ENERGY2          1117
#define IDC_EDIT_DISTANCE               1118
#define IDC_EDIT_1ST_SPEED              1118
#define IDC_EDIT_ANGLE                  1119
#define IDC_EDIT_2ND_SPEED              1119
#define IDC_GRID_WELDCAL                1120
#define IDC_CHECK2                      1121
#define IDC_CHECK_WELDPOINT_CALIB       1121
#define IDC_CHECK_CRING                 1121
#define IDC_CHECK_SHOW_ORIGIN           1121
#define IDC_CHECK_USE_POWER_PROFILE1    1121
#define IDC_CHECK_USE_NGCHECK           1121
#define IDC_CHECK_OUT2IN_P1             1121
#define IDC_STATIC_CHART                1122
#define IDC_CHECK_SHOW_CALIB            1122
#define IDC_CHECK_USE_POWER_PROFILE2    1122
#define IDC_CHECK_OUT2IN_P2             1122
#define IDC_CHECK_USE_NGCHECK2          1122
#define IDC_PICT_LIVE_HISTO             1123
#define IDC_STATIC_GRID                 1123
#define IDC_CHECK_SHOW_MERGED           1123
#define IDC_STATIC_PWGRID               1124
#define IDC_CHECK_SHOW_LEARN            1124
#define IDC_STATIC_PWCHART              1125
#define IDC_EDIT_OFFSET_ANGLE           1126
#define IDC_CHECK_PULSE_SHAPE           1126
#define IDC_STATIC_PULSEGRID            1127
#define IDC_STATIC_FREQ                 1128
#define IDC_STATIC_PULSEWID             1129
#define IDC_COMBO_LENSDB                1133
#define IDC_EDIT_SCAN_X                 1134
#define IDC_EDIT_SCAN_Y                 1135
#define IDC_EDIT_CCD_CAL_STEP           1136
#define IDC_EDIT_LENS_POWER             1137
#define IDC_EDIT_LENS_POWER_X           1137
#define IDC_EDIT_LENS_POWER_Y           1138
#define IDC_STATIC_WELDPATH             1138
#define IDC_EDIT_IMAGE_SCALE_X          1139
#define IDC_EDIT_SERIAL                 1139
#define IDC_EDIT_LENS_POWER_Y2          1140
#define IDC_EDIT_IMAGE_SCALE_Y          1140
#define IDC_RADIO_SWITCH                1141
#define IDC_RADIO_SWITCH1               1142
#define IDC_EDIT_BLOCK_X                1142
#define IDC_RADIO_WELD                  1143
#define IDC_EDIT4                       1143
#define IDC_SPIN_BLOCK_X                1143
#define IDC_RADIO_WELD1                 1144
#define IDC_EDIT_IMGCEN_X               1144
#define IDC_EDIT_BLOCK_Y                1144
#define IDC_RADIO_WELD2                 1145
#define IDC_EDIT_IMGCEN_Y               1145
#define IDC_SPIN_BLOCK_Y                1145
#define IDC_RADIO_MODEL_1               1146
#define IDC_BUTTON_ZOOM_P               1146
#define IDC_RADIO_WELD3                 1146
#define IDC_RADIO_MODEL_2               1147
#define IDC_STATIC_GRID_INSPECTRES      1147
#define IDC_BUTTON_ZOOM_N               1147
#define IDC_RADIO_WELD4                 1147
#define IDC_BUTTON_ZOOM_FIT             1148
#define IDC_STATIC_GRID_INSPECTRES2     1148
#define IDC_RADIO_WELD5                 1148
#define IDC_RADIO_WELD6                 1149
#define IDC_EDIT_GRID_XCNT              1150
#define IDC_EDIT_GRID_YCNT              1151
#define IDC_CHECK_SEL_MODE              1152
#define IDC_EDIT_BLOCK_MOVE_UNIT        1153
#define IDC_BUTTON_BMOVE_X_N            1154
#define IDC_BUTTON_BMOVE_X_P            1155
#define IDC_BUTTON_BMOVE_Y_N            1156
#define IDC_BUTTON_BMOVE_Y_P            1157
#define IDC_STATIC_IMG_WND              1158
#define IDC_RADIO_OCTAGON               1158
#define IDC_STATIC_BLOCK_CNT_X          1159
#define IDC_STATIC_BLOCK_CNT_Y          1160
#define IDC_BUTTON_SEL_BLOCK_LEFT       1161
#define IDC_BUTTON_SEL_BLOCK_RIGHT      1162
#define IDC_BUTTON_SEL_BLOCK_UP         1163
#define IDC_BUTTON_SEL_BLOCK_DOWN       1164
#define IDC_BUTTON_Load_LEARN_IMG       1165
#define IDC_BUTTON_SET_CENTER_BLOCK     1166
#define IDC_BUTTON_CHANGE_CENTER_POS    1167
#define IDC_RADIO_Ell_P1                1171
#define IDC_RADIO_Line_P1               1172
#define IDC_RADIO_Zigzag_P1             1173
#define IDC_RADIO_OCTAGON_P1            1174
#define IDC_RADIO_SPIRAL_P1             1175
#define IDC_LASER_ENABLE                1176
#define IDC_RADIO_Ell_P2                1181
#define IDC_RADIO_Line_P2               1182
#define IDC_RADIO_Zigzag_P2             1183
#define IDC_RADIO_Zigzag2_P2            1184
#define IDC_RADIO_SandGlass_P2          1185
#define IDC_RADIO_SPIRAL_P2             1186
#define IDC_RADIO_1ST_1                 1191
#define IDC_RADIO_1ST_2                 1192
#define IDC_STATIC_BUILD                1193
#define IDC_RADIO_1ST_3                 1193
#define IDC_STATIC_PROJECT              1194
#define IDC_RADIO_1ST_4                 1194
#define IDC_RADIO_1ST_5                 1195
#define IDC_RADIO_1ST_6                 1196
#define IDC_RADIO_1ST_7                 1197
#define IDC_BUTTON_OPEN_WORK            1200
#define IDC_LIST_WORK                   1201
#define IDC_LIST_WORK2                  1202
#define IDC_RADIO_Z_USE                 1203
#define IDC_EDIT_Z_THRESHOLD            1204
#define IDC_EDIT_Z_CNT                  1205
#define IDC_EDIT_Z1_MIN                 1206
#define IDC_EDIT_Z1_MAX                 1207
#define IDC_EDIT_Z1_CNT                 1208
#define IDC_EDIT_Z2_MIN                 1209
#define IDC_RADIO_Z_USE2                1210
#define IDC_EDIT_LEARN_AREA_SX          1211
#define IDC_EDIT_LEGEND_ANG             1211
#define IDC_EDIT_LEARN_AREA_SY          1212
#define IDC_EDIT_LEGEND_DIA             1212
#define IDC_EDIT_LEARN_AREA_EX          1213
#define IDC_EDIT_LEGEND_DIR             1213
#define IDC_EDIT_LEARN_AREA_EY          1214
#define IDC_EDIT_RCP1_SCALE             1214
#define IDC_EDIT_LEARN_AREA_W           1215
#define IDC_EDIT_RCP1_ANGLE             1215
#define IDC_EDIT_LEARN_AREA_H           1216
#define IDC_EDIT_RCP1_OFFSET_X          1216
#define IDC_BUTTON_MOVE_SCALING         1217
#define IDC_EDIT_RCP1_OFFSET_Y          1217
#define IDC_STATIC_X_MIN                1218
#define IDC_EDIT_RCP2_SCALE             1218
#define IDC_STATIC_Y_MIN                1219
#define IDC_CHECK_FIND_DARK_OBJ         1219
#define IDC_EDIT_RCP2_ANGLE             1219
#define IDC_STATIC_X_MAX                1220
#define IDC_BUTTON_SAVE_DATA            1220
#define IDC_CHECK_USE_VIRTUAL_MODE      1220
#define IDC_EDIT_RCP2_OFFSET_X          1220
#define IDC_STATIC_Y_MAX                1221
#define IDC_PASSWORD                    1221
#define IDC_EDIT_RCP2_OFFSET_Y          1221
#define IDC_NEW_PASSWORD                1222
#define IDC_EDIT_RCP3_SCALE             1222
#define IDC_STATIC_GRID_OFFSET          1222
#define IDC_STATIC_GRID_SIZE_PX         1222
#define IDC_CHK_PASSWORD                1223
#define IDC_STATIC_LENS_POWER           1223
#define IDC_EDIT_RCP3_ANGLE             1223
#define IDC_RADIO_INIT_N_SCAN           1223
#define IDC_EDIT_RCP3_OFFSET_X          1224
#define IDC_RADIO_LEARNING              1224
#define IDC_EDIT_RCP3_OFFSET_Y          1225
#define IDC_RADIO_Stiching              1225
#define IDC_EDIT_RCP5_SCALE             1226
#define IDC_RADIO_SAVE                  1226
#define IDC_EDIT_RCP5_ANGLE             1227
#define IDC_EDIT_RCP5_OFFSET_X          1228
#define IDC_EDIT_RCP5_OFFSET_Y          1229
#define IDC_EDIT_Z_PWR                  1230
#define IDC_EDIT_RCP4_SCALE             1234
#define IDC_EDIT_RCP4_ANGLE             1235
#define IDC_EDIT_RCP4_OFFSET_X          1236
#define IDC_EDIT_RCP4_OFFSET_Y          1237
#define IDC_EDIT_RCP6_SCALE             1238
#define IDC_EDIT_RCP6_ANGLE             1239
#define IDC_EDIT_RCP6_OFFSET_X          1240
#define IDC_EDIT_RCP6_OFFSET_Y          1241
#define IDC_STATIC_DLG_AREA             1242
#define IDC_STATIC_MAP                  1243
#define IDC_RADIO_SHOW_ORG              1244
#define IDC_RADIO_CONF_LGRID            1245
#define IDC_RADIO_SHOW_LEARN            1245
#define IDC_RADIO_CONF_SGRID            1246
#define IDC_RADIO_SHOW_CALIB            1246
#define IDC_RADIO_CONF_CGRID            1247
#define IDC_RADIO_SHOW_MERGED           1247
#define IDC_RADIO_DO_LEARN              1248
#define IDC_RADIO_STRETCHING            1249
#define IDC_STATIC_T_BLOCK              1250
#define IDC_COMBO_TARGET_LINE           1251
#define IDC_EDIT_ROI_LEFT               1252
#define IDC_EDIT_ROI_TOP                1253
#define IDC_EDIT_ROI_WIDTH              1254
#define IDC_EDIT_ROI_HEIGHT             1255
#define IDC_EDIT_ROI_EDGE_STRENGTH      1256
#define IDC_COMBO_SEARCH_LINE           1257
#define IDC_STATIC_DIR                  1258
#define IDC_EDIT_RADIUS_BASE            1260
#define IDC_EDIT_RADIUS_HEIGHT          1261
#define IDC_EDIT_PENPOWER               1261
#define IDC_EDIT_HR_RATIO               1262
#define IDC_EDIT_PENSPEED               1262
#define IDC_EDIT_PRGNO                  1262
#define IDC_EDIT_CENTER_OFFSET_X        1263
#define IDC_BUTTON4                     1263
#define IDC_RCP_CHECK                   1263
#define IDC_BTN_SORTIE_MAP              1263
#define IDC_EDIT_CENTER_OFFSET_Y        1264
#define IDC_RADIO_CRING_INOUT           1264
#define IDC_EDIT_1ST_POWER              1265
#define IDC_EDIT_2ND_POWER              1266
#define IDC_EDIT_1ST_LENGTH             1266
#define IDC_EDIT_DEGREE12               1267
#define IDC_EDIT_1ST_WIDTH              1268
#define IDC_EDIT_DEGREE56               1268
#define IDC_CHART_RPT_POWER1            1269
#define IDC_EDIT_1ST_RP                 1269
#define IDC_GRID_RPT_POWER1             1270
#define IDC_EDIT_1ST_PEN                1270
#define IDC_CHART_RPT_POWER2            1271
#define IDC_EDIT8                       1271
#define IDC_GRID_RPT_POWER2             1272
#define IDC_EDIT9                       1272
#define IDC_EDIT10                      1273
#define IDC_EDIT11                      1274
#define IDC_EDIT_CONFIG_ENERGY          1275
#define IDC_STATIC_OVERLENGTH           1276
#define IDC_COMBO_SLOT_NO               1276
#define IDC_STATIC_2ND_WIDTH            1277
#define IDC_COMBO_LAYER_NO              1277
#define IDC_STATIC_2ND_WIDTH1           1277
#define IDC_BUTTON5                     1278
#define IDC_COMBO_PTN_NO                1278
#define IDC_REWORK_SELECT               1278
#define IDC_STATIC_2ND_WIDTH2           1278
#define IDC_LIST_JOB                    1279
#define IDC_BTN_REINIT_PLC              1279
#define IDC_EDIT_START_SLOT             1280
#define IDC_EDIT_DIVISION_OFFSET        1281
#define IDC_STATIC_ROTATE               1281
#define IDC_STATIC_ROTATION_P2          1281
#define IDC_RADIO_RCP_3D                1282
#define IDC_RADIO_RCP_2D                1283
#define IDC_COMBO_MODEL                 1284
#define IDC_COMBO_JIG                   1285
#define IDC_EDIT_HCOMP_REF              1286
#define IDC_EDIT_HCOMP_NGD              1287
#define IDC_EDIT_HCOMP_TC_ANGLE         1288
#define IDC_EDIT_HCOMP_WORK_R           1289
#define IDC_RADIO_3D                    1289
#define IDC_EDIT_HCOMP_WD               1290
#define IDC_RADIO_2D                    1290
#define IDC_EDIT_HCOMP_CEN_X            1291
#define IDC_EDIT_ALL_NUM                1291
#define IDC_EDIT_HCOMP_CEN_Y            1292
#define IDC_BTN_2D_SET                  1292
#define IDC_BTN_HCOMP_TEST              1293
#define IDC_EDIT_HCOMP_NGD2             1293
#define IDC_RADIO_2D_ON                 1294
#define IDC_RADIO_2D_OFF                1295
#define IDC_EDIT_PATH                   1296
#define IDC_BUTTON_OK                   1297
#define IDC_BUTTON_CANCEL               1298
#define IDC_CHECK_USE_REVERSAL          1299
#define IDC_CHECK_CLOSED_P1             1301
#define IDC_CHECK_SORTIE_ENABLE         1302
#define IDC_STATIC_SORITE_CNT           1303
#define IDC_STATIC_SORITE_DIR           1304
#define IDC_CHECK_CLOSED_P2             1306
#define IDC_STATIC_1ST_PINSIZE_01       1307
#define IDC_STATIC_1ST_PINSIZE_02       1308
#define IDC_STATIC_1ST_ZIGZAG_FREQ      1309
#define IDC_STATIC_2ND_ZIGZAG_FREQ      1310
#define IDC_RADIO_SORTIE_DIR            1311
#define IDC_RADIO_SORTIE_DIR2           1312
#define IDC_CHECK_OUTIN_P1              1312
#define IDC_CHECK_CLOSE_P1              1313
#define IDC_CHECK_OUTIN_P2              1314
#define IDC_CHECK_CLOSE_P2              1315
#define IDC_STATIC_FREQ_P1              1316
#define IDC_STATIC_LENGTH_P1            1317
#define IDC_STATIC_WIDTH_P1             1318
#define IDC_STATIC_FREQ_P2              1319
#define IDC_RADIO_2ND_1                 1321
#define IDC_RADIO_2ND_2                 1322
#define IDC_RADIO_2ND_3                 1323
#define IDC_RADIO_2ND_4                 1324
#define IDC_RADIO_2ND_5                 1325
#define IDC_RADIO_2ND_6                 1326
#define IDC_RADIO_2ND_7                 1327
#define IDC_CHECK_USE_SLOTMODE          1328
#define IDC_EDIT_SLOT_NO_1              1329
#define IDC_EDIT_SLOT_NO_2              1330
#define IDC_CHECK3                      1330
#define IDC_CHECK_SORTIE                1330
#define IDC_RADIO_SORITE_DIR            1331
#define IDC_RADIO_SORITE_DIR2           1332
#define IDC_EDIT_SOTIE_CNT              1333
#define IDC_CHECK_SCAN_ENABLE_JIGA      1334
#define IDC_CHECK_SCAN_ENABLE_JIGB      1335
#define IDC_CHECK_SCAN_ENABLE_REWELD    1336
#define IDC_CHECK_SCAN_ENABLE_REWELD_A  1336
#define IDC_STATIC_SORTIE_ENABLE        1337
#define IDC_STATIC_SORTIE_DIR           1338
#define IDC_CHECK_SCAN_ENABLE_REWELD_B  1339
#define IDC_CHECK_SCAN_ENABLE_WELD_A    1340
#define IDC_CHECK_SCAN_ENABLE_WELD_B    1341
#define IDC_EDIT_POS_PATH_JIGA          1342
#define IDC_EDIT_POS_PATH_JIGB          1343
#define IDC_EDIT_MATRIX_DIV_CNT         1344
#define IDC_GRID_SORTIE_MAP             11310
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_ZOOM_EXTENTS          32771
#define ID_BUTTON_CAD_POINT             32772
#define ID_BUTTON_CAD_LINE              32773
#define ID_BUTTON_CAD_POLYLINE          32774
#define ID_BUTTON_CAD_CIRCLE            32775
#define ID_BUTTON_CAD_ARC               32776
#define ID_BUTTON_CAD_EXTEND            32777
#define ID_BUTTON_CAD_TRIM              32778
#define ID_BUTTON_CAD_OFFSET            32779
#define ID_BUTTON_CAD_CHAMFER           32780
#define ID_BUTTON_CAD_ROUND             32781
#define ID_BUTTON_CAD_UNDO              32782
#define ID_BUTTON_CAD_REDO              32783
#define ID_BUTTON_ZOOM_BOX              32784
#define ID_BUTTON_ZOOM_PREV             32785
#define ID_BUTTON_LASER_PENS            32786
#define ID_BUTTON_START_WORK            32787
#define ID_BUTTON_PARAM_SCANNER         32788
#define ID_BUTTON_LOAD_SCOUTIMG         32789
#define ID_BUTTON_CAD_SPIRAL            32790
#define ID_BUTTON_CAD_RECT              32791
#define ID_BUTTON_ZOOM_FITTOWORK        32792
#define ID_BUTTON_MANUAL_SCANNER        32793
#define ID_BUTTON_LASER_START           32795
#define ID_BUTTON_LASER_STOP            32796
#define ID_BUTTON_LASER_GUIDE           32797
#define ID_BUTTON_ELLIPSE               32798
#define ID_BUTTON_HAIRPIN               32799
#define ID_BUTTON_CCDLIIVE              32800
#define ID_FILE_CURR_TO_WORK            32802
#define ID_BUTTON_CAD_ALIGN_HAIRPIN     32803
#define ID_FILE_HP_CONFIG               32804
#define ID_FILE_PEN_IMPORT              32804
#define ID_ACC_VIEW_HOME                32806
#define ID_ACC_VIEW_VISION              32808
#define ID_ACC_VIEW_DRW                 32809
#define ID_ACC_LASERPEN                 32810
#define ID_ACC_VSCAN                    32811
#define ID_ACC_REFIMG_SETTINH           32813
#define ID_ACC_REFIMG_SETTING           32813
#define ID_BUTTON_CAD_HATCH             32815
#define ID_ACC_WELDONCE                 32816
#define ID_FILE_SET_VSCAN               32818
#define ID_BUTTON_SCAN_RNG              32819
#define ID_BUTTON_WELDPATH              32819
#define ID_FILE_IMPORT_DXF              32820
#define ID_FILE_DXF                     32821
#define ID_BUTTON_CAD_JOIN              32822
#define ID_BUTTON_CAD_COPY              32823
#define ID_BUTTON_CAD_SNAP              32824
#define ID_BUTTON_CAD_COPY_RECT         32827
#define ID_BUTTON_CAD_COPY_CIRCLE       32828
#define ID_BUTTON_CAD_ALIGNMENT         32837
#define ID_BUTTON_CAD_ALIGN_LEFT        32838
#define ID_BUTTON_CAD_ALIGN_RIGHT       32839
#define ID_BUTTON_CAD_ALIGN_TOP         32840
#define ID_BUTTON_CAD_ALIGN_BOTTOM      32841
#define ID_BUTTON_CAD_ALIGN_CENTER      32842
#define ID_BUTTON_CAD_KBMOVE            32843
#define ID_BUTTON_COPYMENU              32844
#define ID_BUTTON_CAD_COPY_MOVE         32845
#define ID_BUTTON_HAIRPIN_CONFIG        32858
#define ID_BUTTON_SCAN                  32860
#define ID_BUTTON_HAIRPIN_OFFSET        32860
#define ID_BUTTON_WELD                  32861
#define ID_FILE_SHOW_INSPECT            32862
#define ID_BUTTON_LOGIN                 32863
#define ID_BUTTON_PATTERN               32864
#define ID_FILE_LOCATION_SAVE           32866
#define ID_MATRIX                       32867
#define ID_MATRIX_PCC                   32868
#define ID_BUTTON_2D_RESULT             32869
#define ID_BUTTON2                      32870
#define ID_FILE_LOCATION_LOAD           32870

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        384
#define _APS_NEXT_COMMAND_VALUE         32871
#define _APS_NEXT_CONTROL_VALUE         1345
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
